GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/63d386f43e51ae03c6469a82

###
DELETE http://localhost:3003/api/blogs/63d3889f09febc84b877f00f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZDM4MzFiZTM4MTcxNDBkZDUxZDQ0MiIsImlhdCI6MTY3NDgwNzQwNSwiZXhwIjoxNjc0ODExMDA1fQ.NY2EH6RSzVmTaH7BnxaTuZN0Sptdo_P-2ojM3May0hI

###
PUT http://localhost:3003/api/blogs/63d2159960846a8b6d5c1341
content-type: application/json

{
    "likes": 10
}
