POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
    "title": "test",
    "author": "test user",
    "url": "test@test.com",
    "likes": 9,
    "userId": "63d2749296fddc8d722864f7"
}