GET http://localhost:3003/api/users

###
GET http://localhost:3003/api/users/63d3831be3817140dd51d442

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "root",
    "name": "root user",
    "password": "secret"
}

###

POST http://localhost:3003/api/login
content-type: application/json

{
    "username": "root",
    "password" : "secret"
}

###

POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzZDM4MzFiZTM4MTcxNDBkZDUxZDQ0MiIsImlhdCI6MTY3NDgwNzQwNSwiZXhwIjoxNjc0ODExMDA1fQ.NY2EH6RSzVmTaH7BnxaTuZN0Sptdo_P-2ojM3May0hI

{
    "title": "test",
    "author": "test user",
    "url": "test@test.com",
    "likes": 9,
    "userId": "63d2749296fddc8d722864f7"
}
